### Get All Leads
GET http://localhost:8000/api/leads


### Get Lead By ID
GET http://localhost:8000/api/leads/4

### Create A Lead
POST http://localhost:8000/api/leads
Content-Type: application/json

{
  "Name": "Radha",
  "Company": "Vidheya",
  "Email": "radha@gmail.com"
}